// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	model "beer-review-app/internal/beer/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBeerRepository is an autogenerated mock type for the BeerRepository type
type MockBeerRepository struct {
	mock.Mock
}

// AddComment provides a mock function with given fields: ctx, id, comment
func (_m *MockBeerRepository) AddComment(ctx context.Context, id string, comment model.Comment) error {
	ret := _m.Called(ctx, id, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.Comment) error); ok {
		r0 = rf(ctx, id, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, beer
func (_m *MockBeerRepository) Create(ctx context.Context, beer *model.Beer) error {
	ret := _m.Called(ctx, beer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Beer) error); ok {
		r0 = rf(ctx, beer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBeerRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, id, commentID
func (_m *MockBeerRepository) DeleteComment(ctx context.Context, id string, commentID string) error {
	ret := _m.Called(ctx, id, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecInTx provides a mock function with given fields: ctx, fn
func (_m *MockBeerRepository) ExecInTx(ctx context.Context, fn func(context.Context, BeerRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, BeerRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAdminStats provides a mock function with given fields: ctx
func (_m *MockBeerRepository) GetAdminStats(ctx context.Context) (*AdminStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminStats")
	}

	var r0 *AdminStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*AdminStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *AdminStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AdminStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0
func (_m *MockBeerRepository) GetAll(_a0 context.Context) ([]model.Beer, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Beer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Beer, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Beer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockBeerRepository) GetByID(ctx context.Context, id string) (model.Beer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Beer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Beer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Beer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Beer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginated provides a mock function with given fields: ctx, page, pageSize
func (_m *MockBeerRepository) GetPaginated(ctx context.Context, page int, pageSize int) ([]model.Beer, int, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginated")
	}

	var r0 []model.Beer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Beer, int, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.Beer); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUserStats provides a mock function with given fields: ctx, userID
func (_m *MockBeerRepository) GetUserStats(ctx context.Context, userID string) (*UserStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStats")
	}

	var r0 *UserStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*UserStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *UserStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchBeers provides a mock function with given fields: ctx, filters
func (_m *MockBeerRepository) SearchBeers(ctx context.Context, filters model.BeerFilters) ([]model.Beer, int, bool, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchBeers")
	}

	var r0 []model.Beer
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BeerFilters) ([]model.Beer, int, bool, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BeerFilters) []model.Beer); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BeerFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.BeerFilters) bool); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, model.BeerFilters) error); ok {
		r3 = rf(ctx, filters)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Update provides a mock function with given fields: ctx, id, beer
func (_m *MockBeerRepository) Update(ctx context.Context, id string, beer model.Beer) error {
	ret := _m.Called(ctx, id, beer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.Beer) error); ok {
		r0 = rf(ctx, id, beer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBeerRepository creates a new instance of MockBeerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeerRepository {
	mock := &MockBeerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
