// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	model "beer-review-app/internal/beer/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockDeletionRequestRepository is an autogenerated mock type for the DeletionRequestRepository type
type MockDeletionRequestRepository struct {
	mock.Mock
}

// CreateDeletionRequest provides a mock function with given fields: ctx, req
func (_m *MockDeletionRequestRepository) CreateDeletionRequest(ctx context.Context, req *model.BeerDeletionRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeletionRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.BeerDeletionRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDeletionRequests provides a mock function with given fields: ctx, filter
func (_m *MockDeletionRequestRepository) GetDeletionRequests(ctx context.Context, filter model.DeletionRequestFilter) ([]model.BeerDeletionRequest, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetDeletionRequests")
	}

	var r0 []model.BeerDeletionRequest
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DeletionRequestFilter) ([]model.BeerDeletionRequest, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DeletionRequestFilter) []model.BeerDeletionRequest); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerDeletionRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DeletionRequestFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.DeletionRequestFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResolveDeletionRequest provides a mock function with given fields: ctx, reqID, status, reviewedBy, reviewedAt
func (_m *MockDeletionRequestRepository) ResolveDeletionRequest(ctx context.Context, reqID string, status string, reviewedBy *string, reviewedAt time.Time) error {
	ret := _m.Called(ctx, reqID, status, reviewedBy, reviewedAt)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDeletionRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, time.Time) error); ok {
		r0 = rf(ctx, reqID, status, reviewedBy, reviewedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDeletionRequestRepository creates a new instance of MockDeletionRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeletionRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeletionRequestRepository {
	mock := &MockDeletionRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
