// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	model "beer-review-app/internal/beer/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockReportRepository is an autogenerated mock type for the ReportRepository type
type MockReportRepository struct {
	mock.Mock
}

// CreateReport provides a mock function with given fields: ctx, report
func (_m *MockReportRepository) CreateReport(ctx context.Context, report *model.BeerReport) error {
	ret := _m.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.BeerReport) error); ok {
		r0 = rf(ctx, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetReports provides a mock function with given fields: ctx, filter
func (_m *MockReportRepository) GetReports(ctx context.Context, filter model.ReportFilter) ([]model.BeerReport, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetReports")
	}

	var r0 []model.BeerReport
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ReportFilter) ([]model.BeerReport, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ReportFilter) []model.BeerReport); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ReportFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.ReportFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetReportsByBeerID provides a mock function with given fields: ctx, beerID, limit, offset
func (_m *MockReportRepository) GetReportsByBeerID(ctx context.Context, beerID string, limit int, offset int) ([]model.BeerReport, int, error) {
	ret := _m.Called(ctx, beerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetReportsByBeerID")
	}

	var r0 []model.BeerReport
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]model.BeerReport, int, error)); ok {
		return rf(ctx, beerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []model.BeerReport); ok {
		r0 = rf(ctx, beerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, beerID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, beerID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResolveReport provides a mock function with given fields: ctx, reportID, status, resolvedBy, resolvedAt
func (_m *MockReportRepository) ResolveReport(ctx context.Context, reportID string, status string, resolvedBy *string, resolvedAt time.Time) error {
	ret := _m.Called(ctx, reportID, status, resolvedBy, resolvedAt)

	if len(ret) == 0 {
		panic("no return value specified for ResolveReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, time.Time) error); ok {
		r0 = rf(ctx, reportID, status, resolvedBy, resolvedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockReportRepository creates a new instance of MockReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportRepository {
	mock := &MockReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
