// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	model "beer-review-app/internal/beer/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockModerationRepository is an autogenerated mock type for the ModerationRepository type
type MockModerationRepository struct {
	mock.Mock
}

// CreateDeletionRequest provides a mock function with given fields: ctx, req
func (_m *MockModerationRepository) CreateDeletionRequest(ctx context.Context, req *model.BeerDeletionRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeletionRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.BeerDeletionRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateReport provides a mock function with given fields: ctx, report
func (_m *MockModerationRepository) CreateReport(ctx context.Context, report *model.BeerReport) error {
	ret := _m.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.BeerReport) error); ok {
		r0 = rf(ctx, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecInTx provides a mock function with given fields: ctx, fn
func (_m *MockModerationRepository) ExecInTx(ctx context.Context, fn func(context.Context, ModerationRepository, BeerRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, ModerationRepository, BeerRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDeletionRequests provides a mock function with given fields: ctx, filter
func (_m *MockModerationRepository) GetDeletionRequests(ctx context.Context, filter model.DeletionRequestFilter) ([]model.BeerDeletionRequest, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetDeletionRequests")
	}

	var r0 []model.BeerDeletionRequest
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DeletionRequestFilter) ([]model.BeerDeletionRequest, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DeletionRequestFilter) []model.BeerDeletionRequest); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerDeletionRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DeletionRequestFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.DeletionRequestFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetReports provides a mock function with given fields: ctx, filter
func (_m *MockModerationRepository) GetReports(ctx context.Context, filter model.ReportFilter) ([]model.BeerReport, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetReports")
	}

	var r0 []model.BeerReport
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ReportFilter) ([]model.BeerReport, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ReportFilter) []model.BeerReport); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ReportFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.ReportFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetReportsByBeerID provides a mock function with given fields: ctx, beerID, limit, offset
func (_m *MockModerationRepository) GetReportsByBeerID(ctx context.Context, beerID string, limit int, offset int) ([]model.BeerReport, int, error) {
	ret := _m.Called(ctx, beerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetReportsByBeerID")
	}

	var r0 []model.BeerReport
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]model.BeerReport, int, error)); ok {
		return rf(ctx, beerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []model.BeerReport); ok {
		r0 = rf(ctx, beerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, beerID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, beerID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResolveDeletionRequest provides a mock function with given fields: ctx, reqID, status, reviewedBy, reviewedAt
func (_m *MockModerationRepository) ResolveDeletionRequest(ctx context.Context, reqID string, status string, reviewedBy *string, reviewedAt time.Time) error {
	ret := _m.Called(ctx, reqID, status, reviewedBy, reviewedAt)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDeletionRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, time.Time) error); ok {
		r0 = rf(ctx, reqID, status, reviewedBy, reviewedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResolveReport provides a mock function with given fields: ctx, reportID, status, resolvedBy, resolvedAt
func (_m *MockModerationRepository) ResolveReport(ctx context.Context, reportID string, status string, resolvedBy *string, resolvedAt time.Time) error {
	ret := _m.Called(ctx, reportID, status, resolvedBy, resolvedAt)

	if len(ret) == 0 {
		panic("no return value specified for ResolveReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, time.Time) error); ok {
		r0 = rf(ctx, reportID, status, resolvedBy, resolvedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockModerationRepository creates a new instance of MockModerationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModerationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModerationRepository {
	mock := &MockModerationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
