// Code generated by mockery v2.53.6. DO NOT EDIT.

package moderation

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockModerator is an autogenerated mock type for the Moderator type
type MockModerator struct {
	mock.Mock
}

// IsContentAllowed provides a mock function with given fields: ctx, text
func (_m *MockModerator) IsContentAllowed(ctx context.Context, text string) (bool, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for IsContentAllowed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, text)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockModerator creates a new instance of MockModerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModerator {
	mock := &MockModerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
