// Code generated by mockery v2.53.6. DO NOT EDIT.

package moderation

import mock "github.com/stretchr/testify/mock"

// MockOpenAIModeratorOption is an autogenerated mock type for the OpenAIModeratorOption type
type MockOpenAIModeratorOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockOpenAIModeratorOption) Execute(_a0 *OpenAIModerator) {
	_m.Called(_a0)
}

// NewMockOpenAIModeratorOption creates a new instance of MockOpenAIModeratorOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenAIModeratorOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenAIModeratorOption {
	mock := &MockOpenAIModeratorOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
