// Code generated by mockery v2.53.6. DO NOT EDIT.

package moderation

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockModerationCache is an autogenerated mock type for the ModerationCache type
type MockModerationCache struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockModerationCache) Get(ctx context.Context, key string) (bool, bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Set provides a mock function with given fields: ctx, key, value
func (_m *MockModerationCache) Set(ctx context.Context, key string, value bool) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockModerationCache creates a new instance of MockModerationCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModerationCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModerationCache {
	mock := &MockModerationCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
