// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase

import (
	model "beer-review-app/internal/beer/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockModerationUsecase is an autogenerated mock type for the ModerationUsecase type
type MockModerationUsecase struct {
	mock.Mock
}

// GetDeletionRequests provides a mock function with given fields: ctx, filter
func (_m *MockModerationUsecase) GetDeletionRequests(ctx context.Context, filter model.DeletionRequestFilter) ([]model.BeerDeletionRequest, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetDeletionRequests")
	}

	var r0 []model.BeerDeletionRequest
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DeletionRequestFilter) ([]model.BeerDeletionRequest, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DeletionRequestFilter) []model.BeerDeletionRequest); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerDeletionRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DeletionRequestFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.DeletionRequestFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetReports provides a mock function with given fields: ctx, filter
func (_m *MockModerationUsecase) GetReports(ctx context.Context, filter model.ReportFilter) ([]model.BeerReport, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetReports")
	}

	var r0 []model.BeerReport
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ReportFilter) ([]model.BeerReport, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ReportFilter) []model.BeerReport); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ReportFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.ReportFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetReportsByBeerID provides a mock function with given fields: ctx, beerID, limit, offset
func (_m *MockModerationUsecase) GetReportsByBeerID(ctx context.Context, beerID string, limit int, offset int) ([]model.BeerReport, int, error) {
	ret := _m.Called(ctx, beerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetReportsByBeerID")
	}

	var r0 []model.BeerReport
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]model.BeerReport, int, error)); ok {
		return rf(ctx, beerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []model.BeerReport); ok {
		r0 = rf(ctx, beerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, beerID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, beerID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReportBeer provides a mock function with given fields: ctx, beerID, userID, input
func (_m *MockModerationUsecase) ReportBeer(ctx context.Context, beerID string, userID string, input model.BeerReportInput) error {
	ret := _m.Called(ctx, beerID, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for ReportBeer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.BeerReportInput) error); ok {
		r0 = rf(ctx, beerID, userID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestDeletion provides a mock function with given fields: ctx, beerID, userID, input
func (_m *MockModerationUsecase) RequestDeletion(ctx context.Context, beerID string, userID string, input model.BeerDeletionRequestInput) error {
	ret := _m.Called(ctx, beerID, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeletion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.BeerDeletionRequestInput) error); ok {
		r0 = rf(ctx, beerID, userID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResolveDeletionRequest provides a mock function with given fields: ctx, reqID, status, adminID
func (_m *MockModerationUsecase) ResolveDeletionRequest(ctx context.Context, reqID string, status string, adminID string) error {
	ret := _m.Called(ctx, reqID, status, adminID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDeletionRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, reqID, status, adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResolveReport provides a mock function with given fields: ctx, reportID, status, adminID
func (_m *MockModerationUsecase) ResolveReport(ctx context.Context, reportID string, status string, adminID string) error {
	ret := _m.Called(ctx, reportID, status, adminID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, reportID, status, adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockModerationUsecase creates a new instance of MockModerationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModerationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModerationUsecase {
	mock := &MockModerationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
