// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase

import (
	model "beer-review-app/internal/beer/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockBeerUsecase is an autogenerated mock type for the BeerUsecase type
type MockBeerUsecase struct {
	mock.Mock
}

// AddComment provides a mock function with given fields: ctx, id, comment
func (_m *MockBeerUsecase) AddComment(ctx context.Context, id string, comment model.Comment) error {
	ret := _m.Called(ctx, id, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.Comment) error); ok {
		r0 = rf(ctx, id, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddMedia provides a mock function with given fields: ctx, id, item
func (_m *MockBeerUsecase) AddMedia(ctx context.Context, id string, item model.MediaItem) ([]model.MediaItem, error) {
	ret := _m.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for AddMedia")
	}

	var r0 []model.MediaItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.MediaItem) ([]model.MediaItem, error)); ok {
		return rf(ctx, id, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.MediaItem) []model.MediaItem); ok {
		r0 = rf(ctx, id, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MediaItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.MediaItem) error); ok {
		r1 = rf(ctx, id, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, beer
func (_m *MockBeerUsecase) Create(ctx context.Context, beer *model.Beer) error {
	ret := _m.Called(ctx, beer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Beer) error); ok {
		r0 = rf(ctx, beer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBeerUsecase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, id, commentID
func (_m *MockBeerUsecase) DeleteComment(ctx context.Context, id string, commentID string) error {
	ret := _m.Called(ctx, id, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockBeerUsecase) GetAll(ctx context.Context) ([]model.Beer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Beer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Beer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Beer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockBeerUsecase) GetByID(ctx context.Context, id string) (model.Beer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Beer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Beer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Beer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Beer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginated provides a mock function with given fields: ctx, page, pageSize
func (_m *MockBeerUsecase) GetPaginated(ctx context.Context, page int, pageSize int) ([]model.Beer, int, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginated")
	}

	var r0 []model.Beer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Beer, int, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.Beer); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LikeComment provides a mock function with given fields: ctx, beerID, commentID, userID, deviceID
func (_m *MockBeerUsecase) LikeComment(ctx context.Context, beerID string, commentID string, userID string, deviceID string) error {
	ret := _m.Called(ctx, beerID, commentID, userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, beerID, commentID, userID, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListBeerEvents provides a mock function with given fields: ctx, beerID, since
func (_m *MockBeerUsecase) ListBeerEvents(ctx context.Context, beerID string, since time.Time) ([]model.BeerEvent, error) {
	ret := _m.Called(ctx, beerID, since)

	if len(ret) == 0 {
		panic("no return value specified for ListBeerEvents")
	}

	var r0 []model.BeerEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]model.BeerEvent, error)); ok {
		return rf(ctx, beerID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []model.BeerEvent); ok {
		r0 = rf(ctx, beerID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeerEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, beerID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchBeers provides a mock function with given fields: ctx, filters
func (_m *MockBeerUsecase) SearchBeers(ctx context.Context, filters model.BeerFilters) ([]model.Beer, int, bool, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchBeers")
	}

	var r0 []model.Beer
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BeerFilters) ([]model.Beer, int, bool, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BeerFilters) []model.Beer); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BeerFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.BeerFilters) bool); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, model.BeerFilters) error); ok {
		r3 = rf(ctx, filters)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Update provides a mock function with given fields: ctx, id, beer
func (_m *MockBeerUsecase) Update(ctx context.Context, id string, beer model.Beer) error {
	ret := _m.Called(ctx, id, beer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.Beer) error); ok {
		r0 = rf(ctx, id, beer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBeerUsecase creates a new instance of MockBeerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeerUsecase {
	mock := &MockBeerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
