// Code generated by mockery v2.53.6. DO NOT EDIT.

package storage

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUploader is an autogenerated mock type for the Uploader type
type MockUploader struct {
	mock.Mock
}

// Upload provides a mock function with given fields: ctx, objectName, contentType, data
func (_m *MockUploader) Upload(ctx context.Context, objectName string, contentType string, data []byte) (string, error) {
	ret := _m.Called(ctx, objectName, contentType, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) (string, error)); ok {
		return rf(ctx, objectName, contentType, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) string); ok {
		r0 = rf(ctx, objectName, contentType, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = rf(ctx, objectName, contentType, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockUploader creates a new instance of MockUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploader {
	mock := &MockUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
